/*
===============================================
REEL DEFINITIONS
===============================================
Physical and virtual reel configurations
- Physical reel: 22 stops (visual strip)
- Virtual reels: 72 stops (for weighting)
===============================================
*/

// Physical reel (22 stops) - the actual visual strip
export const PHYSICAL_REEL = [
  "BLANK_A", "SEVEN_A", "BLANK_B", "SINGLE_BAR_A",
  "BLANK_C", "DOUBLE_DIAMOND_A", "BLANK_D", "TRIPLE_BAR_A",
  "BLANK_E", "CHERRY_A", "BLANK_F", "DOUBLE_BAR_A",
  "BLANK_G", "SEVEN_B", "BLANK_H", "SINGLE_BAR_B",
  "BLANK_I", "DOUBLE_DIAMOND_B", "BLANK_J", "TRIPLE_BAR_B",
  "BLANK_K", "DOUBLE_BAR_B"
];

// Maps physical stop IDs to display symbols
export const PHYSICAL_STOP_SYMBOL = {
  BLANK_A: "BLANK", BLANK_B: "BLANK", BLANK_C: "BLANK", BLANK_D: "BLANK",
  BLANK_E: "BLANK", BLANK_F: "BLANK", BLANK_G: "BLANK", BLANK_H: "BLANK",
  BLANK_I: "BLANK", BLANK_J: "BLANK", BLANK_K: "BLANK",
  SINGLE_BAR_A: "SINGLE_BAR", SINGLE_BAR_B: "SINGLE_BAR",
  DOUBLE_BAR_A: "DOUBLE_BAR", DOUBLE_BAR_B: "DOUBLE_BAR",
  TRIPLE_BAR_A: "TRIPLE_BAR", TRIPLE_BAR_B: "TRIPLE_BAR",
  SEVEN_A: "SEVEN", SEVEN_B: "SEVEN",
  DOUBLE_DIAMOND_A: "DOUBLE_DIAMOND", DOUBLE_DIAMOND_B: "DOUBLE_DIAMOND",
  CHERRY_A: "CHERRY"
};

// Virtual reels (72 stops each) - used for weighted RNG
export const VIRTUAL_REELS = {
  REEL1: [
    "BLANK_A", "SINGLE_BAR_A", "BLANK_B", "SINGLE_BAR_B", "DOUBLE_BAR_A",
    "SINGLE_BAR_A", "SINGLE_BAR_B", "BLANK_C", "TRIPLE_BAR_A", "BLANK_D",
    "BLANK_E", "BLANK_F", "DOUBLE_BAR_B", "BLANK_G", "SINGLE_BAR_A",
    "BLANK_H", "SINGLE_BAR_B", "SEVEN_A", "BLANK_I", "SINGLE_BAR_A",
    "BLANK_J", "DOUBLE_DIAMOND_A", "BLANK_K", "BLANK_A", "SINGLE_BAR_B",
    "SINGLE_BAR_A", "BLANK_B", "BLANK_C", "SINGLE_BAR_B", "BLANK_D",
    "CHERRY_A", "SINGLE_BAR_A", "BLANK_E", "SINGLE_BAR_B", "DOUBLE_BAR_A",
    "BLANK_F", "BLANK_G", "SINGLE_BAR_A", "DOUBLE_BAR_B", "SINGLE_BAR_B",
    "BLANK_H", "SINGLE_BAR_A", "SEVEN_B", "BLANK_I", "SINGLE_BAR_B",
    "BLANK_J", "BLANK_K", "BLANK_A", "SINGLE_BAR_A", "BLANK_B",
    "SINGLE_BAR_B", "DOUBLE_BAR_A", "BLANK_C", "SINGLE_BAR_A", "SINGLE_BAR_B",
    "TRIPLE_BAR_B", "BLANK_D", "SINGLE_BAR_A", "BLANK_E", "DOUBLE_BAR_B",
    "BLANK_F", "BLANK_G", "SINGLE_BAR_B", "BLANK_H", "BLANK_I",
    "BLANK_J", "SINGLE_BAR_A", "BLANK_K", "SINGLE_BAR_B", "BLANK_A",
    "DOUBLE_BAR_A", "BLANK_B"
  ],
  REEL2: [
    "BLANK_A", "SINGLE_BAR_A", "BLANK_B", "SINGLE_BAR_B", "DOUBLE_BAR_A",
    "SINGLE_BAR_A", "SINGLE_BAR_B", "BLANK_C", "TRIPLE_BAR_A", "BLANK_D",
    "BLANK_E", "BLANK_F", "DOUBLE_BAR_B", "BLANK_G", "SINGLE_BAR_A",
    "BLANK_H", "SINGLE_BAR_B", "SEVEN_A", "BLANK_I", "SINGLE_BAR_A",
    "BLANK_J", "DOUBLE_DIAMOND_A", "BLANK_K", "BLANK_A", "SINGLE_BAR_B",
    "SINGLE_BAR_A", "BLANK_B", "BLANK_C", "SINGLE_BAR_B", "BLANK_D",
    "CHERRY_A", "SINGLE_BAR_A", "BLANK_E", "SINGLE_BAR_B", "DOUBLE_BAR_A",
    "BLANK_F", "BLANK_G", "SINGLE_BAR_A", "DOUBLE_BAR_B", "SINGLE_BAR_B",
    "BLANK_H", "SINGLE_BAR_A", "SEVEN_B", "BLANK_I", "SINGLE_BAR_B",
    "BLANK_J", "BLANK_K", "BLANK_A", "SINGLE_BAR_A", "BLANK_B",
    "SINGLE_BAR_B", "DOUBLE_BAR_A", "BLANK_C", "SINGLE_BAR_A", "SINGLE_BAR_B",
    "TRIPLE_BAR_B", "BLANK_D", "SINGLE_BAR_A", "BLANK_E", "DOUBLE_BAR_B",
    "BLANK_F", "BLANK_G", "SINGLE_BAR_B", "BLANK_H", "BLANK_I",
    "BLANK_J", "SINGLE_BAR_A", "BLANK_K", "SINGLE_BAR_B", "BLANK_A",
    "DOUBLE_BAR_A", "BLANK_B"
  ],
  REEL3: [
    "BLANK_A", "SINGLE_BAR_A", "BLANK_B", "SINGLE_BAR_B", "DOUBLE_BAR_A",
    "SINGLE_BAR_A", "SINGLE_BAR_B", "BLANK_C", "TRIPLE_BAR_A", "BLANK_D",
    "BLANK_E", "BLANK_F", "DOUBLE_BAR_B", "BLANK_G", "SINGLE_BAR_A",
    "BLANK_H", "SINGLE_BAR_B", "SEVEN_A", "BLANK_I", "SINGLE_BAR_A",
    "BLANK_J", "DOUBLE_DIAMOND_A", "BLANK_K", "BLANK_A", "SINGLE_BAR_B",
    "SINGLE_BAR_A", "BLANK_B", "BLANK_C", "SINGLE_BAR_B", "BLANK_D",
    "CHERRY_A", "SINGLE_BAR_A", "BLANK_E", "SINGLE_BAR_B", "DOUBLE_BAR_A",
    "BLANK_F", "BLANK_G", "SINGLE_BAR_A", "DOUBLE_BAR_B", "SINGLE_BAR_B",
    "BLANK_H", "SINGLE_BAR_A", "SEVEN_B", "BLANK_I", "SINGLE_BAR_B",
    "BLANK_J", "BLANK_K", "BLANK_A", "SINGLE_BAR_A", "BLANK_B",
    "SINGLE_BAR_B", "DOUBLE_BAR_A", "BLANK_C", "SINGLE_BAR_A", "SINGLE_BAR_B",
    "TRIPLE_BAR_B", "BLANK_D", "SINGLE_BAR_A", "BLANK_E", "DOUBLE_BAR_B",
    "BLANK_F", "BLANK_G", "SINGLE_BAR_B", "BLANK_H", "BLANK_I",
    "BLANK_J", "SINGLE_BAR_A", "BLANK_K", "SINGLE_BAR_B", "BLANK_A",
    "DOUBLE_BAR_A", "BLANK_B"
  ]
};